// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JJndqx5gkmxEk8XvnV6RA92r12Tf5hc',
    appId: '1:238659540610:android:9ed43ee8e438eac467069b',
    messagingSenderId: '238659540610',
    projectId: 'root-arcanum-450614-t5',
    storageBucket: 'root-arcanum-450614-t5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBktXnxx3yvQwTsD-MSuMUvJPf6hcwXMy8',
    appId: '1:238659540610:ios:85162c0f78e76da967069b',
    messagingSenderId: '238659540610',
    projectId: 'root-arcanum-450614-t5',
    storageBucket: 'root-arcanum-450614-t5.firebasestorage.app',
    androidClientId: '238659540610-bqrkc1882bdfc0jvvu49kqc27fm1i84j.apps.googleusercontent.com',
    iosClientId: '238659540610-66gftvi6s2t1re6fjtd0ta0t8nti5ufk.apps.googleusercontent.com',
    iosBundleId: 'ng.rapidapp.mobile',
  );
}
