import 'package:flutter/material.dart';

class AppColors {
  static const Color primary = Color(0xFF007AFF);
  static const Color primaryDark = Color(0xFF004EB0);
  static const Color primaryDisabled = Color(0xFF106CD0);
  static const Color fadedPrimary = Color(0xFFEDF2F9);
  static const Color secondaryHeading = Color(0xff767676);
  static const Color btnGrey = Color(0xFFEFEFEF);
  static const Color greyPrimary = Color(0xffBFBFC1);
  static const Color greyLight = Color(0xFFF4F4F4);
  static const Color textGrey = Color(0xFFC4C3C5);
  static const Color textMediumGrey = Color(0xFF9CA3AF);
  static const Color textDarkGrey = Color(0xFF595959);
  static const Color textVeryDarkGrey = Color(0xFF424242);
  static const Color scaffoldBg = Color(0xFFF9FAFB);
  static const Color txtFadedBlue = Color(0xff8FC4FF);
  static const Color primaryTxtFieldBg = Color(0xffF3F3F3);
  static const Color secondaryTxtFieldBg = Color(0xffF9F9F9);
  static const Color black400 = Color(0xff3D3E3E);
  static const Color black300 = Color(0xff6E6E6E);
  static const Color black200 = Color(0xff9E9F9F);
  static const Color yellow = Color(0xffFFDA03);
  static const Color green = Color(0xff00963D);
  static const Color green2 = Color(0xff34BB78);
  static const Color red = Color(0xffFF2100);
  static const Color blue = Color(0xff004EB0);
  static const Color grey800 = Color(0xff4C4C4D);
  static const Color grey600 = Color(0xff99999A);
  static const Color grey500 = Color(0xff8C8C8C);
  static const Color grey400 = Color(0xff797979);
  static const Color grey200 = Color(0xffE5E5E5);
  static const Color grey100 = Color(0xffF2F2F3);
  static const Color selectedNavBar = Color(0xffEDFFFD);
  static const Color hintGrey = Color(0xffB8B8B8);
  static const Color borderColor2 = Color(0xffE5E7EB);
  static const Color borderColor = Color(0xffECECEC);
  static Color white20 = const Color(0xFFFFFFFF).withValues(alpha: 0.2);
  static const Color offWhite = Color(0xffF9FAFB);
  static const Color tertiaryOrange = Color(0xffF59E0B);
  static const Color tertiaryGreen = Color(0xff10B981);
  static const Color tertiaryRed = Color(0xffEF4444);
  static const Color lightBlue = Color(0xffDBEAFE);
  static const Color connectDirectBlue = Color(0xFF4EA3FF);
  static const Color connectObdBlue = Color(0xFF074180);
}
